### ISSUE TITLE
Need  file to convert Yolov4-tiny.weights to .h5 format 

### ISSUE THREAD

**Issue by shahzebali457** [bubbliiiing/yolov4-tiny-keras#6]
Hi bubbling, I want to convert yolov4 tiny weights to h5 format. Did you have a code for converting files to h5 format? 
If then please share that one.
Thanks

**Comment by bubbliiiing** [comment]
Sorry, I delete it, I can not do well in converting, So I trained myself.

**Comment by bubbliiiing** [comment]
Next week, I will up load a COCO weights trained by myself, It maybe help for u?
